const fs = require('fs'), crypto = require('crypto');
const salt = Buffer.from('pandel-settings-v1', 'utf8');
const key = crypto.scryptSync(process.env.ADMIN_PASSWORD || 'pandel-default-key', salt, 32, { N: 16384, r: 8, p: 1 });
const raw = JSON.parse(fs.readFileSync('/home/ubuntu/app/coolink/data/settings.json', 'utf8'));
const buf = Buffer.from(raw.data, 'base64');
const dec = crypto.createDecipheriv('aes-256-gcm', key, buf.subarray(0, 12));
dec.setAuthTag(buf.subarray(12, 28));
const s = JSON.parse(Buffer.concat([dec.update(buf.subarray(28)), dec.final()]).toString('utf8'));
const { extractToken } = require('/home/ubuntu/app/coolink/server/providers/login-123.js');
(async () => {
  const tk = extractToken(s.cookies.pan123 || '');
  const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36';
  const H = { 'User-Agent': UA, authorization: 'Bearer ' + tk, platform: 'web', 'app-version': '3', Origin: 'https://www.123pan.com', Referer: 'https://www.123pan.com/' };
  const qs = 'shareKey=' + encodeURIComponent('nbicMh-Z27Xh') + '&sharePwd=' + encodeURIComponent('9Aut') + '&ParentFileId=0&Page=1&limit=100&orderBy=fileId&orderDirection=asc&next=0';
  const r = await fetch('https://api.123pan.cn/api/share/get?' + qs, { headers: H });
  const j = await r.json().catch(() => ({}));
  console.log('share/get → HTTP', r.status, '| code:', j.code);
  const data = j.data || {};
  const keys = Object.keys(data);
  console.log('data 字段:', keys.join(', '));
  const detail = data.DetailList || data.detailList || [];
  const file = data.FileList || data.fileList || [];
  console.log('DetailList 数:', detail.length, '| FileList 数:', file.length);
  if (detail.length) console.log('DetailList[0]:', JSON.stringify(detail[0]).slice(0, 300));
  if (file.length) console.log('FileList[0]:', JSON.stringify(file[0]).slice(0, 200));
})().catch(e => console.log('ERR:', e.message));
